<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-8GD78RI5" failures="1" tests="1" name="Default test(failed)(failed)" time="19.006" errors="0" timestamp="2023-10-17T10:14:14 IST">
  <testcase classname="com.Tests.LoginTests" name="validateLogo" time="1.166">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.Tests.LoginTests.validateLogo(LoginTests.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateLogo -->
  <testcase classname="com.Tests.LoginTests" name="ValidateTitle" time="0.0">
    <ignored/>
  </testcase> <!-- ValidateTitle -->
  <testcase classname="com.Tests.LoginTests" name="ValidateURL" time="0.0">
    <ignored/>
  </testcase> <!-- ValidateURL -->
  <testcase classname="com.Tests.LoginTests" name="LoginWithValidCredential" time="0.0">
    <ignored/>
  </testcase> <!-- LoginWithValidCredential -->
</testsuite> <!-- Default test(failed)(failed) -->
